### ISSUE TITLE
Crash when opening craft list

### ISSUE THREAD

**Issue by m13253** [PunishXIV/Artisan#116]
### Steps to reproduce:
1. Add anything to a new craft list
2. Left click the craft list to open it

### What happened:
* A lot of identical error messages pop up.
  After that, a new message box pops up every second.
  FFXIV becomes inoperable and has to exit.
  ![screenshot](https://github.com/user-attachments/assets/9639c0e4-cbfa-4b00-a1fd-0bc4a5369f46)

### Versions:
* FFXIV 7.1
* Artisan v4.0.2.6
* Dalamud version D11.0.0.0

### Stack trace:
```
Unhandled exception on AppDomain
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'rowId')
Actual value was 1647.
   at Lumina.Excel.ExcelSheet`1.GetRow(UInt32 rowId)
   at Artisan.GameInterop.ItemStats..ctor(UInt32 ItemId, Boolean hq, Span`1 materia, Span`1 materiaGrades) in C:\Users\thero\source\repos\Artisan\Artisan\GameInterop\CharacterStats.cs:line 95
   at Artisan.GameInterop.CharacterStats.GetBaseStatsEquipped() in C:\Users\thero\source\repos\Artisan\Artisan\GameInterop\CharacterStats.cs:line 199
   at Artisan.GameInterop.CharacterStats.GetBaseStatsForClassHeuristic(Job job) in C:\Users\thero\source\repos\Artisan\Artisan\GameInterop\CharacterStats.cs:line 230
   at Artisan.UI.ListEditor.DrawRecipeSettings() in C:\Users\thero\source\repos\Artisan\Artisan\UI\ListEditor.cs:line 1267
   at OtterGui.ItemDetailsWindow.Draw(String label, Action drawHeader, Action drawDetails) in C:\Users\thero\source\repos\Artisan\OtterGui\ItemSelector.cs:line 490
   at Artisan.UI.ListEditor.DrawRecipes() in C:\Users\thero\source\repos\Artisan\Artisan\UI\ListEditor.cs:line 1074
   at Artisan.UI.ListEditor.Draw() in C:\Users\thero\source\repos\Artisan\Artisan\UI\ListEditor.cs:line 244
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
Please tell me if you need more information from my log file, as I don’t plan to upload my log file to a public place.

### List of other installed plugins:
* Accountant v1.7.0.0
* Allagan Tools v1.11.0.1
* BilingualTooltips v1.0.2.0
* ChatCoordinates v2.1.2.6
* ezMiniCactpot v2.1.0.0
* FPS Plugin v1.7.0.1
* GatherBuddy v3.5.0.1
* Market board v1.9.0.0
* MidiBard 2 v2.6.2.0
* Orchestrion Plugin v2.2.0.9
* PingPlugin v2.8.0.0
* Price Insight v2.11.1.0
* Remote Party Finder Uploader v1.0.14.0
* Simple Tweaks Plugin v1.10.3.5
* Who Did That? v1.7.1.0

**Comment by m13253** [comment]
Artisan v3.0.2.8 seems to no longer have this issue. Closing.
